#!/bin/sh
#
# Start the shared dir with the host
#

mkdir -p /root/shared

case "$1" in
  start)
	printf "Mounting shared dir: "
	mount -t 9p -o trans=virtio host /root/shared
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Unmounting shared dir: "
	sync
	umount /root/shared
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?


